version: '3.8'

services:
  app-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    environment:
      - HTTP_ADDRESS=0.0.0.0:8080
      - RAFT_NODE_ID=1
      - RAFT_BIND_ADDRESS=0.0.0.0:8081
      - RAFT_ADVERTISE_ADDRESS=localhost:8081
      - CONNECTION_STRING=postgresql://postgres:admin@host.docker.internal:5432/Raft1?sslmode=disable
    ports:
      - "5001:8080"
      - "5081:8081"

  app-2:
    image: app
    environment:
      - HTTP_ADDRESS=0.0.0.0:8080
      - RAFT_NODE_ID=2
      - RAFT_BIND_ADDRESS=0.0.0.0:8081
      - RAFT_ADVERTISE_ADDRESS=localhost:8081
      - CONNECTION_STRING=postgresql://postgres:admin@host.docker.internal:5432/Raft2?sslmode=disable
    ports:
      - "5002:8080"
      - "5082:8081"

  app-3:
    image: app
    environment:
      - HTTP_ADDRESS=0.0.0.0:8080
      - RAFT_NODE_ID=3
      - RAFT_BIND_ADDRESS=0.0.0.0:8081
      - RAFT_ADVERTISE_ADDRESS=localhost:8081
      - CONNECTION_STRING=postgresql://postgres:admin@host.docker.internal:5432/Raft3?sslmode=disable
    ports:
      - "5003:8080"
      - "5083:8081"