version: '3.8'

services:
  app-0:
    image: app
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - RAFT_NODE_ID=0
      - CONNECTION_STRING=postgresql://postgres:admin@localhost:5432/Raft1
    ports:
      - "5001:8080"

  app-1:
    image: app
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - RAFT_NODE_ID=1
      - CONNECTION_STRING=postgresql://postgres:admin@localhost:5432/Raft2
    ports:
      - "5002:8080"

  app-2:
    image: app
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - RAFT_NODE_ID=2
      - CONNECTION_STRING=postgresql://postgres:admin@localhost:5432/Raft3
    ports:
      - "5003:8080"